# Copyright (c) 2015, NVIDIA CORPORATION.  All rights reserved.

language: python
python:
    2.7
compiler: gcc   # for Caffe
sudo: required  # for Caffe
env:
    global:
        # Make
        - NUM_THREADS=4
        # Caffe
        - WITH_CUDA=true # Installs CUDA, doesn't build it
        - WITH_CMAKE=false
before_install:
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    - export PATH=/home/travis/miniconda/bin:/usr/local/cuda/bin:$PATH
install:
    # Caffe
    - ./scripts/travis/install-caffe.sh $(pwd)/deps/caffe

    # XXX
    - conda list
    - pip list

    # Torch
    #    - ./scripts/travis/install-torch.sh $(pwd)/deps/torch

    # DIGITS
    - sudo apt-get install graphviz
    # conda (fast)
    - conda install --quiet --yes gevent greenlet
    # pip (slow)
    - pip install --quiet -r requirements.txt
    - pip install -r requirements_test.txt

    # XXX
    - conda list
    - pip list

before_script:
    - export CAFFE_HOME=$(pwd)/deps/caffe
    - export TORCH_HOME=$(pwd)/deps/torch
script:
    ./digits-test --with-coverage --cover-package=tools,digits
after_success:
    coveralls
